### ISSUE TITLE
SimpleKendraStackのNodejsBuildでエラー

### ISSUE THREAD

**Issue by takashikami** [aws-samples/simple-lex-kendra-jp#42]
### 発生したエラー内容
Kendraを体験するためにとても良いサンプルだと思い、自分の環境にデプロイしてKendraを広めたいと考えております。
しかしながら、SimpleKendraStackのデプロイでエラーとなってしまいました。
```
CREATE_FAILED        | Custom::CDKNodejsBuild                          | WebKendraXXXXXXXX
Received response status [FAILED] from custom resource. Message returned: Command failed: npm install -w web-kendra && npm run build -w web-kendra
```

CloudWatch Logsに吐き出されたカスタムリソースのログ（抜粋）は以下でした。
```
npm ERR! code EMFILE
npm ERR! syscall open
npm ERR! path /tmp/.npm/_cacache/index-v5/e3/09/052e58a6075087e9c7afd3a4af787bcf2c704c7ea0c6919d678da6f94093
npm ERR! errno -24
npm ERR! EMFILE: too many open files, open '/tmp/.npm/_cacache/index-v5/e3/09/052e58a6075087e9c7afd3a4af787bcf2c704c7ea0c6919d678da6f94093'
npm ERR! A complete log of this run can be found in:
npm ERR! /tmp/.npm/_logs/2023-05-08T06_05_47_090Z-debug-0.log
Command failed: npm install -w web-kendra && npm run build -w web-kendra at checkExecSyncError (node:child_process:885:11) at execSync (node:child_process:957:15) at Runtime.handler (/var/task/index.js:4659:41) { status: 232, signal: null, output: [ null, null, null ], pid: 24, stdout: null, stderr: null }
```

### 実行したコードのバージョン
`ae0ebb36ac59f6b15512136add8941f717da74da`

### 再現性のある手順
```
git clone https://github.com/aws-samples/simple-lex-kendra-jp
cd simple-lex-kendra-jp
npm install -ws
npm exec -w cdk -- cdk bootstrap
npm exec -w cdk -- cdk deploy SimpleKendraStack
```

### 実行環境
> Windows10 WSL2 Ubuntu 22.04 + Docker Desktop
> node v18.16.0 (npm v9.5.1)
> cdk version: 2.77.0 (build 06a0b19)

**Comment by wadabee** [comment]
@takashikami 
ご連絡ありがとうございます！
npm もしくは、Lambdaのアップデートの影響を受けて、フロントエンドのビルドに失敗する様になっておりました（申し訳ございませんが、詳細は不明です）。
Codebuildを利用して、デプロイするように変更を行いました。

プログラムを最新にした上で、再度デプロイしていただけないでしょうか。
ご確認のほど、よろしくお願いします。

**Comment by wadabee** [comment]
補足です。
直接的なエラーの原因は、Lambdaの開けるファイル上限（File descriptors = 1024）を超えたためです。
こちらの制約はハードリミットとなり、変更不可となります。
[参考：Lambda quotas](https://docs.aws.amazon.com/lambda/latest/dg/gettingstarted-limits.html)

**Comment by takashikami** [comment]
高アジリティ対応、ありがとうございます！
修正いただいたバージョン（3fb778f）で、SimpleKendraStackのデプロイは成功しました。

しかしながら、手順書を進めていくと、期待する結果でないことが２つありましたので、別イシューで上げさせていただきます。せっかくですので、動作させたいと思います。お付き合いいただけますと、ありがたいですし、うれしく思います。
