### ISSUE TITLE
SimpleKendraStack.KendraSampleFrontend の URL へのアクセスで 403 ERROR

### ISSUE THREAD

**Issue by takashikami** [aws-samples/simple-lex-kendra-jp#44]
「03_DEPLOY_KENDRA.md#データの取り込み」に記述してある通り、AWS CDK が出力した SimpleKendraStack.KendraSampleFrontend の URL にアクセスしたのですが、以下の通り403 ERRORが表示されました。
何か足りない手順がありますでしょうか。

403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
Generated by cloudfront (CloudFront)

### 再現できる手順

1. SimpleKendraStackのデプロイが成功
2. [Amazon Kendra](https://console.aws.amazon.com/kendra/home) を開き、simple-index-by-cdk を選択して、左カラムの Data sources から s3-data-source をクリックし、右上の Sync now をクリックして、同期を実施。
3. SimpleKendraStack.KendraSampleFrontend の URL にアクセス

**Comment by wadabee** [comment]
@takashikami 
問題のご報告、ありがとうございます！

当サンプルコードは、WAFによるアクセス制御を行っております。
IPアドレス制限のルールを設定しているのですが、IPv4のルールしか設定しておりませんでしたので、IPv6のルールを追加しました。
※サンプルコードですので、すべてのIPアドレスを許可する設定となっております。
プログラムを最新化の上、ご確認の程よろしくお願いします。

もし、当事象が解消しませんでしたら、お手数ですがご連絡の程よろしくお願いします。

**Comment by takashikami** [comment]
迅速にご対応いただき、ありがとうございます。
最新版をPULLしてデプロイしたところ、アクセスできました！
