### ISSUE TITLE
SimpleLexV2Stackのデプロイでエラー

### ISSUE THREAD

**Issue by takashikami** [aws-samples/simple-lex-kendra-jp#45]
SimpleKendraStackのデプロイが成功した後、s3-data-sourceを同期た後、SimpleLexV2Stackをデプロイすると、以下のエラー（抜粋）が発生しました。

```
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
Bundling asset SimpleLexV2Stack/FulfillmentFunction/Code/Stage...
esbuild cannot run locally. Switching to Docker bundling.

  asset-output/index.js  1.8kb

⚡ Done in 2ms
Including dependency stacks: webAcl, SimpleKendraStack
[Error at /SimpleLexV2Stack/WebLexV2/Project/Resource] AwsSolutions-CB4: The CodeBuild project does not use an AWS KMS key for encryption.

Found errors
```

### 再現手順
1. SimpleKendraStackのデプロイが成功
2. s3-data-sourceを同期
3. 以下のコマンドを実行
```
npm exec -w cdk -- cdk deploy SimpleLexV2Stack
```

**Comment by wadabee** [comment]
こちらのリポジトリのサンプル実装は、[cdk-nag](https://github.com/cdklabs/cdk-nag)という仕組みを導入して、セキュリティチェックを行っております。
(参考:AWS Cloud Development Kit と cdk-nag でアプリケーションのセキュリティとコンプライアンスを管理する)[https://aws.amazon.com/jp/blogs/news/manage-application-security-and-compliance-with-the-aws-cloud-development-kit-and-cdk-nag/]

#42 の対応を行った際に、Lex Stackの対応が漏れておりました。申し訳ございません。
プログラムを最新化の上、ご確認の程よろしくお願いします。

**Comment by takashikami** [comment]
最新版をPULLしてデプロイしたところ、最後まで処理が進み、デプロイが完了しました。
SimpleLexV2Stack.LexV2SampleFrontendのURLにアクセスしたところ、問題なく動作することを確認しました。
このLexのプログラムはもちろん、CDKについてもテクニックが満載なので、勉強になります。
素早い対応、本当にありがとうございました。
